移植下載Sponsor圖片
COSCUP/2024 pull request #13
Opened 2024-04-03 18:54 UTC by Spyup

- Close #7

2024-04-03 18:54 UTC, Spyup commented
更動：
- 移植從 Google Sheet 下載 Sponsor 圖片 [2023-static](https://github.com/COSCUP/2023-static)
- 建立 Workflow

作用：手動驅動 Workflow 下載 Sponsor 圖片

待研究：自動更新

2024-05-25 20:05 UTC, mirumodapon requested changes

2024-05-25 20:05 UTC, mirumodapon commented on .github/workflows/SponsorImg.yml
感覺這個要寫進 Deploy.yml?

2024-05-25 20:05 UTC, mirumodapon commented on scripts/tools/downloadSponsorImg.ts
> +import get from 'lodash/get'
這個依賴好像是錯的
現在專案裡的 lodash 是 lodash_es

2024-05-25 20:05 UTC, mirumodapon commented on scripts/tools/downloadSponsorImg.ts
> +      key: process.env.SPREADSHEET_API_KEY,
這裡的 key 沒有導入，所以會吃不到 key

2024-05-25 20:30 UTC, mirumodapon requested changes

2024-05-25 20:30 UTC, mirumodapon commented on package.json
> -    "@types/google-spreadsheet": "^3.3.1",
這個為什麼要刪掉呀

2024-05-25 21:04 UTC, merged