顯示且能修改時區的議程表
COSCUP/2024 pull request #15
Opened 2024-04-09 10:05 UTC by rileychh

從 [COSCUP/2022 #21](https://github.com/COSCUP/2022/pull/21) 搬過來的 PR，合併了衝突，還沒測試過。

關閉 #2 。

2024-04-30 09:26 UTC, mirumodapon requested changes
- 選擇器會在 navbar 的上方，可能需要調整 z-index
- 我覺得可以調整一下在 width < 600px 選擇器的顯示
- 我覺得可以把選好的時區存進 localStrage 就不用每次都要重選

2024-04-30 09:26 UTC, mirumodapon commented on src/modules/session/logic.ts
> +        const span = Math.abs(endIndex - startIndex)
是有 session 有這方面的錯誤嗎？

2024-04-30 09:26 UTC, mirumodapon commented on src/modules/session/logic.ts
> +// FIXME: 這段如果有辦法的話可以轉為框架做法？
應該是要轉成框架做法，有興趣可以改

2024-04-30 09:26 UTC, mirumodapon commented on src/pages/Session.vue
> +      <button
或許可以回到會場(台灣)時區？這部分之後可以討論一下

2024-04-30 09:26 UTC, mirumodapon commented on src/components/Session/ScheduleItem.vue
> +    currentTimeZone: {
想確認一下這裡為什麼需要傳這個參數

2024-04-30 09:57 UTC, rileychh commented on src/modules/session/logic.ts
> +// FIXME: 這段如果有辦法的話可以轉為框架做法？
這段留言是搬運過來的，我不知道「框架做法」是什麼意思 ;)

2024-04-30 11:32 UTC, mirumodapon commented on src/modules/session/logic.ts
> +// FIXME: 這段如果有辦法的話可以轉為框架做法？
就是不要用 html string 的做法。這個可以先放著

2024-05-06 13:45 UTC, yoyo930021 commented on src/modules/session/logic.ts
> +        const span = Math.abs(endIndex - startIndex)
這個貌似去年我改的，某個 bug

2024-05-09 13:48 UTC, rileychh commented on src/modules/session/logic.ts
> +        const span = Math.abs(endIndex - startIndex)
我不確定這個修改的作用，它也是搬過來的 😅
該留著還是改回來？

2024-05-09 13:50 UTC, rileychh commented on src/pages/Session.vue
> +      <button
該把重設按鈕從當地時區改成會場時區，還是另外加一個按鈕？

2024-05-09 13:52 UTC, rileychh commented on src/components/Session/ScheduleItem.vue
> +    currentTimeZone: {
看起來沒有用到，另外兩個元件也是相同的情況。我把他們移除了。

2024-05-09 14:14 UTC, rileychh commented
> 選擇器會在 navbar 的上方，可能需要調整 z-index

為了在 [教室列表](https://github.com/COSCUP/2024/blob/99e5097f81d85a632df4ccfc162bd0e7004b9b89/src/assets/scss/components/session/_schedule-table.scss#L26) （`z-index: 2`） 之上，我設成了 `z-index: 3`。建議該怎麽處理呢？

> 我覺得可以調整一下在 width < 600px 選擇器的顯示

雖然不知道為什麼無法置中，但大概用 `white-space: nowrap` 和 `max-width` 處理好了。

> 我覺得可以把選好的時區存進 localStrage 就不用每次都要重選

搞定。

2024-05-26 15:06 UTC, mirumodapon commented on src/pages/Session.vue
> +      <button
我覺得選一個就好耶！

2024-05-26 15:07 UTC, mirumodapon commented on src/modules/session/logic.ts
> +        const span = Math.abs(endIndex - startIndex)
先...改回來好了 XD

2024-05-26 15:07 UTC, mirumodapon commented
> > 選擇器會在 navbar 的上方，可能需要調整 z-index
> 
> 為了在 [教室列表](https://github.com/COSCUP/2024/blob/99e5097f81d85a632df4ccfc162bd0e7004b9b89/src/assets/scss/components/session/_schedule-table.scss#L26) （`z-index: 2`） 之上，我設成了 `z-index: 3`。建議該怎麽處理呢？
> 
> > 我覺得可以調整一下在 width < 600px 選擇器的顯示
> 
> 雖然不知道為什麼無法置中，但大概用 `white-space: nowrap` 和 `max-width` 處理好了。
> 
> > 我覺得可以把選好的時區存進 localStrage 就不用每次都要重選
> 
> 搞定。

z-index 設成 0 看起來 OK，教室列表之上是什麼意思啊

2024-05-27 13:07 UTC, rileychh commented
![圖片](https://github.com/COSCUP/2024/assets/53939195/45925098-e35d-4ce4-9390-46385c65234e)
⬆️ `.time-zone-container { z-index: 0; }` 長這樣

![圖片](https://github.com/COSCUP/2024/assets/53939195/b8405080-f94d-4143-92b4-cb203c88337b)
⬆️ `.time-zone-container { z-index: 3; }` 長這樣

2024-05-27 13:16 UTC, rileychh commented on src/pages/Session.vue
> +      <button
在 fb51b6f736fcd71af4bd97c26558920d19f11a4a 改成會場時區了

2024-05-27 13:17 UTC, rileychh commented on src/modules/session/logic.ts
> +        const span = Math.abs(endIndex - startIndex)
在 7f72694a7b60d8fd2f9b6ea902d0904077c8a32a 改回來了

2024-07-04 15:56 UTC, rileychh commented
謝謝 @mirumodapon 幫忙修好 z-index 的問題！
我再加上了修改時區後清除輸入的功能，用起來更方便。

2024-07-16 13:08 UTC, merged