增加 OG Image 產生功能
COSCUP/2024 pull request #16
Opened 2024-04-30 06:26 UTC by j36426052

解決 #3 的其中一個方案：)
之後會再調整背景圖片

2024-04-30 08:36 UTC, mirumodapon requested changes
希望可以在開發模式下，不用一定需要有檔案

2024-04-30 08:36 UTC, mirumodapon commented on .env
> +VITE_LANDING_ONLY=false
目前網站一程表還沒有要上線，測試完記得改回去喔！

2024-04-30 08:36 UTC, mirumodapon commented on src/modules/metas/index.ts
可以使用原本的 title 就好了喔！

2024-04-30 08:36 UTC, mirumodapon commented on vite.config.ts
在我電腦裡跑好像沒有正常被觸發生成

2024-04-30 09:17 UTC, j36426052 commented
> 希望可以在開發模式下，不用一定需要有檔案

指的是 session.json 嗎？不太清楚是哪個檔案

2024-04-30 09:40 UTC, mirumodapon commented
> > 希望可以在開發模式下，不用一定需要有檔案
> 
> 指的是 session.json 嗎？不太清楚是哪個檔案

就是 og 的那張圖片，好像開發模式下，沒有 og 的那張圖會報錯。

2024-04-30 11:38 UTC, j36426052 commented
有多設定，當沒有 session 這個資料夾會自己加上去，應該可以動了！

2024-05-30 02:21 UTC, Spyup commented
執行發現有多位講者的時候會有問題，像是Session ID 3RY9JG 這場
![image](https://github.com/COSCUP/2024/assets/16890512/7816fc08-d96e-448c-b03e-6c13bb8a34c4)

2024-06-05 10:56 UTC, j36426052 commented
> 希望可以在開發模式下，不用一定需要有檔案

這邊設定好了

2024-07-28 15:48 UTC, merged