Scheduling conflicts
COSCUP/2024 pull request #18
Opened 2024-05-06 13:37 UTC by bessyhuang

2024-05-27 16:10 UTC, rileychh requested changes
記得要用 ESLint 檢查過程式碼再提交，這樣其他開發者才不會在未來執行 ESLint 時不小心動到這裡喔！

功能沒有問題，但是按鈕的顏色對比（灰底白字）太低了，有些人可能會看不清楚。試試看調整背景顏色。

除了顏色對比，有沒有辦法為按鈕加上一些敘述來明定用意呢？一個辦法是利用 [title 屬性](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title)。

2024-05-27 16:10 UTC, rileychh commented on src/components/Session/SessionFilter.vue
> +      </button>
```suggestion
    <button class="fab CalendarMultipleCheck" :class="{ active }" @click="checkMySchedule">
      <icon-mdi-calendar-multiple-check />
    </button>
    <template v-if="!isFilterCollection">
```

- 沒有條件的 `class` 可以不用寫在 `v-bind` 裡面
- icon 元件因為沒有內容，可以寫成 self-closing
- 如果這個按鈕不受 `v-if` 的條件影響，直接放在 `<article>` 底下就可以了

2024-05-27 16:10 UTC, rileychh commented on src/components/Session/SessionFilter.vue
> +      </button>
```suggestion
```
承上

2024-05-27 16:10 UTC, rileychh commented on src/components/Session/SessionFilter.vue
> +      var isConflict = false;
```suggestion
      let isConflict = false;
```

用 [let](https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Statements/let) 來宣告區域變數。

2024-05-27 16:10 UTC, rileychh commented on src/components/Session/SessionFilter.vue
> +      const events: any[] = [];
考慮為 `events` 定義型別。從下面的 `push`，看起來他的型別是
```ts
interface SessionTimeSpan {
  startTime: Date;
  endTime: Date;
}
```

2024-05-27 16:10 UTC, rileychh commented on src/components/Session/SessionFilter.vue
> +      }
```suggestion
      comparisonLoop:
      for (let i = 0; i < events.length - 1; i++) {
        for (let j = i + 1; j < events.length; j++) {
          const eventA = events[i];
          const eventB = events[j];
          if ( 
            (eventA["endTime"] > eventB["startTime"] && eventA["startTime"] < eventB["endTime"]) || 
            (eventB["endTime"] > eventA["startTime"] && eventB["startTime"] < eventA["endTime"]) 
          ) {
            isConflict = true;
            break comparisonLoop;
          }
        }
      }
```

可以利用 labels 在發現衝突時提早離開迴圈，加快計算速度。
[StackOverflow 上的說明](https://stackoverflow.com/a/183197/11631322)

2024-05-27 16:10 UTC, rileychh commented on src/components/Session/SessionFilter.vue
> +      favoriteSessions.value.forEach(function(SessionId) {
既然 `checkMySchedule` 是[箭頭函式](https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Functions/Arrow_functions)了，要不要把這個 forEach 的回呼函式也寫成箭頭呢？
吹毛求疵：`SessionId` 引數應該是小寫開頭。

2024-05-27 16:10 UTC, rileychh commented on locales/en/session.json
> +  "share_no_favorites": "There are no favorite sessions to share at the moment.",
```suggestion
  "share_no_favorites": "There are no favorite sessions to share.",
```

這樣寫應該更符合中文版的原意 :)

2024-06-16 09:27 UTC, bessyhuang commented on src/components/Session/SessionFilter.vue
> +      </button>
在 [319f36a](https://github.com/COSCUP/2024/commit/319f36abeb768f25f36e16f453ce48467e215084) 用 ESLint 跑過了，也為按鈕新增文字提示（title 屬性）、調整背景顏色。

2024-06-16 09:39 UTC, bessyhuang commented on locales/en/session.json
> +  "share_no_favorites": "There are no favorite sessions to share at the moment.",
[241a8a0](https://github.com/COSCUP/2024/commit/241a8a0e3fce9f95c490ef78038b0055432e7fb4) 已調整 😄

2024-06-16 10:10 UTC, bessyhuang commented on src/components/Session/SessionFilter.vue
> +      }
原本想試試 Use label 的方法，但 ESLint 檢查會跑不過（error: Unexpected labeled statement & Unexpected label in break statement），因此就換其他方式了。

調整後結果，見 [9debe0d](https://github.com/COSCUP/2024/commit/9debe0daccc49b64c031c9113218654066dca9ac)

2024-07-04 14:59 UTC, rileychh commented on src/components/Session/SessionFilter.vue
> +      </button>
看起來都沒問題了👍
建議之後的 CSS Class 用比較常見的 kebab-case 命名法喔

2024-07-04 15:12 UTC, rileychh commented on src/components/Session/SessionFilter.vue
> +      }
我想到的一個做法，可以參考看看：
```ts
const checkMySchedule = () => {
  const events = favoriteSessions.value.map((sessionId) => {
    const session = getSessionById(sessionId)
    return { startTime: new Date(session.start), endTime: new Date(session.end) }
  })

  const isConflicting = () => {
    for (let i = 0; i < events.length - 1; i++) {
      for (let j = i + 1; j < events.length; j++) {
        const eventA = events[i]
        const eventB = events[j]
        if (
          (eventA.endTime > eventB.startTime && eventA.startTime < eventB.endTime) ||
          (eventB.endTime > eventA.startTime && eventB.startTime < eventA.endTime)
        ) {
          return true
        }
      }
    }
    return false
  }

  if (isConflicting()) {
    window.alert(t('session.schedule_conflicts'))
  } else {
    window.alert(t('session.schedule_no_conflicts'))
  }
}
```

1. 直接把 `favoriteSessions` map 成 `events`: 這樣就不用定義型別，TS 能自行從 `map` 推論
2. 把檢查用巢狀迴圈寫成函數: 避開需要使用標籤或旗幟的問題

2024-07-04 15:17 UTC, rileychh requested changes
再把[這個部分](https://github.com/COSCUP/2024/pull/18#discussion_r1665836834)討論好就大功告成了🎉 加油💪

2024-07-04 15:17 UTC, rileychh commented on src/components/Session/SessionFilter.vue
> +
如果參考了[我的提案](https://github.com/COSCUP/2024/pull/18#discussion_r1665836834)的話，這裡可以移除

2024-07-14 16:57 UTC, bessyhuang commented on src/components/Session/SessionFilter.vue
> +      }
哇！code 真的乾淨許多，謝謝你。
我採用了你的做法，見 [cccb9a8](https://github.com/COSCUP/2024/commit/cccb9a83fc845360e439608e7e5319ff3cae868d)

2024-07-14 16:58 UTC, bessyhuang commented on src/components/Session/SessionFilter.vue
> +
我採用了你的做法，見 [cccb9a8](https://github.com/COSCUP/2024/commit/cccb9a83fc845360e439608e7e5319ff3cae868d)，謝謝你！

2024-07-15 07:07 UTC, rileychh approved these changes

2024-07-28 15:48 UTC, merged